export const opcodes = {
	// OPCODE 0: System & String
	NOOP: { padded: false, opcode: 0, args: [], m1: 0 },
	HALT: { padded: false, opcode: 0, args: [], m1: 1 },
	CMOD: { padded: false, opcode: 0, args: ["mod"], bits: [10], m1: 2 },
	SRPR: {
		padded: true,
		opcode: 0,
		args: ["reg", "indoffset3"],
		bits: [7, 4, 0],
		m1: 4,
	},
	SREV: { padded: true, opcode: 0, args: ["indoffset6"], bits: [0], m1: 5 },
	SVAL: {
		padded: true,
		opcode: 0,
		args: ["reg", "indoffset3"],
		bits: [7, 0],
		m1: 6,
	},

	// OPCODE 1: Data & Stack
	LDIR: { padded: true, opcode: 1, args: ["reg", "imm16"], bits: [16, 0] },
	LDIF: { padded: false, opcode: 1, args: ["flg4"], bits: [0], m1: 0 },
	PSHI: { padded: false, opcode: 1, args: ["imm10"], bits: [0], m1: 1 },
	PUSH: { padded: false, opcode: 1, args: ["reg/ind"], bits: [0], m1: 2 },
	POP: { padded: false, opcode: 1, args: ["reg/ind"], bits: [0], m1: 3 },
	STRI: {
		padded: false,
		opcode: 1,
		args: ["imm7", "reg"],
		bits: [0, 7],
		m1: 4,
	},
	LODI: {
		padded: false,
		opcode: 1,
		args: ["reg", "imm7"],
		bits: [7, 0],
		m1: 5,
	},
	BOOL: {
		padded: false,
		opcode: 1,
		args: ["flg4", "reg/ind"],
		bits: [4, 0],
		m1: 6,
	},

	// OPCODE 2: Arithmetic
	AND: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 0,
	},
	OR: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 1,
	},
	XOR: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 2,
	},
	NOT: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg"],
		bits: [10, 4],
		m4: 3,
	},
	ADD: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 4,
	},
	SUB: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 5,
	},
	MUL: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 6,
	},
	DIV: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 7,
	},
	MOD: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 8,
	},
	POW: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 9,
	},
	SIN: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg"],
		bits: [10, 4],
		m4: 10,
	},
	COS: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg"],
		bits: [10, 4],
		m4: 11,
	},
	ASIN: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg"],
		bits: [10, 4],
		m4: 12,
	},
	ACOS: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg"],
		bits: [10, 4],
		m4: 13,
	},
	ATAN: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg"],
		bits: [10, 4],
		m4: 14,
	},
	LERP: {
		padded: false,
		opcode: 2,
		args: ["reg", "reg", "reg"],
		bits: [10, 7, 4],
		m4: 15,
	},

	// OPCODE 3: Memory & Register Operations
	MOVE: {
		padded: false,
		opcode: 3,
		args: ["reg", "reg"],
		bits: [7, 4],
		m1: 0,
	},
	SWAP: {
		padded: false,
		opcode: 3,
		args: ["reg", "reg"],
		bits: [7, 4],
		m1: 1,
	},
	STRE: {
		padded: false,
		opcode: 3,
		args: ["indoffset3", "reg"],
		bits: [7, 4, 0],
		m1: 2,
	},
	LOAD: {
		padded: false,
		opcode: 3,
		args: ["reg", "indoffset3"],
		bits: [7, 0],
		m1: 3,
	},
	COMP: {
		padded: false,
		opcode: 3,
		args: ["reg", "reg"],
		bits: [7, 4],
		m1: 4,
	},
	SHFT: {
		padded: false,
		opcode: 3,
		args: ["sft2", "reg", "imm4"],
		bits: [7, 4, 0],
		m1: 5,
	},
	XCHG: {
		padded: false,
		opcode: 3,
		args: ["ind", "reg"],
		bits: [7, 4],
		m1: 6,
	},
	INCR: {
		padded: false,
		opcode: 3,
		args: ["reg/ind"],
		bits: [0],
		m1: 7,
		m2: 0,
	},
	DECR: {
		padded: false,
		opcode: 3,
		args: ["reg/ind"],
		bits: [0],
		m1: 7,
		m2: 1,
	},

	// OPCODE 4: Flow & I/O
	JUMP: {
		padded: false,
		opcode: 4,
		args: ["reg", "flg4"],
		bits: [4, 0],
		m1: 0,
		m2: 0,
	},
	JUMR: {
		padded: false,
		opcode: 4,
		args: ["reg", "flg4"],
		bits: [4, 0],
		m1: 0,
		m2: 1,
	},
	CALL: {
		padded: false,
		opcode: 4,
		args: ["reg", "flg4"],
		bits: [4, 0],
		m1: 1,
		m2: 0,
	},
	CALR: {
		padded: false,
		opcode: 4,
		args: ["reg", "flg4"],
		bits: [4, 0],
		m1: 1,
		m2: 1,
	},
	INTR: {
		padded: false,
		opcode: 4,
		args: ["flg4", "imm2", "imm4"],
		bits: [6, 4, 0],
		m1: 2,
	},
	IRET: { padded: false, opcode: 4, args: ["flg4"], bits: [0], m1: 3 },
	RETN: { padded: false, opcode: 4, args: ["flg4"], bits: [0], m1: 4 },
	INPT: { padded: false, opcode: 4, args: ["reg/ind"], bits: [0], m1: 5 },
	OUTP: {
		padded: false,
		opcode: 4,
		args: ["reg", "imm4"],
		bits: [4, 0],
		m1: 6,
	},
	DISP: {
		padded: false,
		opcode: 4,
		args: ["disp2"],
		bits: [0],
		m1: 7,
		m2: 0,
	},
	PERI: {
		padded: false,
		opcode: 4,
		args: ["peri2", "reg/ind"],
		bits: [4, 0],
		m1: 7,
		m2: 1,
	},

	// OPCODE 5: Math Functions
	SQRT: {
		padded: false,
		opcode: 5,
		args: ["reg/ind", "reg/ind"],
		bits: [4, 0],
		m1: 0,
	},
	LOGN: {
		padded: false,
		opcode: 5,
		args: ["reg/ind", "reg/ind"],
		bits: [4, 0],
		m1: 1,
	},
	ABSV: {
		padded: false,
		opcode: 5,
		args: ["reg/ind", "reg/ind"],
		bits: [4, 0],
		m1: 2,
	},
	FLOR: {
		padded: false,
		opcode: 5,
		args: ["reg/ind", "reg/ind"],
		bits: [4, 0],
		m1: 3,
	},
	CEIL: {
		padded: false,
		opcode: 5,
		args: ["reg/ind", "reg/ind"],
		bits: [4, 0],
		m1: 4,
	},
	FMAC: {
		padded: false,
		opcode: 5,
		args: ["reg", "reg", "reg"],
		bits: [7, 4, 0],
		m1: 5,
	},
	SIGN: {
		padded: false,
		opcode: 5,
		args: ["reg/ind", "reg/ind"],
		bits: [4, 0],
		m1: 6,
	},
	ROND: {
		padded: false,
		opcode: 5,
		args: ["reg/ind", "reg/ind"],
		bits: [4, 0],
		m1: 7,
	},

	// OPCODE 6: Buffer & Audio Operations
	BCLR: { padded: false, opcode: 6, args: ["imm1"], bits: [9], m1: 0 },
	BLEN: {
		padded: false,
		opcode: 6,
		args: ["imm1", "reg/ind"],
		bits: [9, 0],
		m1: 1,
	},
	BDEL: {
		padded: false,
		opcode: 6,
		args: ["imm1", "reg/ind"],
		bits: [9, 0],
		m1: 2,
	},
	BUPD: {
		padded: false,
		opcode: 6,
		args: ["imm1", "imm5", "reg/ind"],
		bits: [9, 4, 0],
		m1: 3,
	},
	STSC: {
		padded: false,
		opcode: 6,
		args: ["ind", "imm4"],
		bits: [4, 0],
		m1: 4,
	},
	PSSC: { padded: false, opcode: 6, args: ["imm4"], bits: [0], m1: 5 },
	SPSC: { padded: false, opcode: 6, args: ["imm4"], bits: [0], m1: 6 },
	RPSC: { padded: false, opcode: 6, args: ["imm4"], bits: [0], m1: 7 },

	// OPCODE 7: System Memory
	SMEM: { padded: false, opcode: 7, args: ["mem1"], bits: [0], m1: 0 },
	INTM: { padded: false, opcode: 7, args: ["imm1"], bits: [0], m1: 1 },
	RAND: { padded: false, opcode: 7, args: ["reg/ind"], bits: [0], m1: 2 },
	CAST: {
		padded: false,
		opcode: 7,
		args: ["reg/ind", "reg/ind"],
		bits: [4, 0],
		m1: 3,
	},
	LDBL: {
		padded: false,
		opcode: 7,
		args: ["ind", "reg/ind"],
		bits: [4, 0],
		m1: 4,
	},
	LDBI: {
		padded: false,
		opcode: 7,
		args: ["ind", "imm7"],
		bits: [7, 0],
		m1: 5,
	},
	WRBL: {
		padded: false,
		opcode: 7,
		args: ["ind", "reg/ind"],
		bits: [4, 0],
		m1: 6,
	},
	WRBI: {
		padded: false,
		opcode: 7,
		args: ["ind", "imm7"],
		bits: [7, 0],
		m1: 7,
	},
};
